version: "3"
services:
  postgres-db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=auth,postgres:home,postgres #{dbname}:{user}
    env_file:
      - .env.example
    volumes:
      - ./postgres_db/dbdata:/var/lib/postgresql/data
      - ./postgres_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
  gateway-service:
    image: gateway-service
    container_name: gateway-service
    environment:
      - PORT=3000
      - SECRET_KEY=test
    env_file:
      - .env.example
    depends_on:
      - auth-service
      - home-apis
    build:
      context: ./packages/gateway-service
      dockerfile: Dockerfile
    ports:
      - 3816:3000

  auth-service:
    image: auth-service
    container_name: auth-service
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres-db:5432/auth
      - PORT=3000
      - JWT_SECRET=test
      - NODE_ENV=local
    env_file:
      - .env.example
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    ports:
      - 3817:3000

  home-apis:
    image: home-apis
    container_name: home-apis
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres-db:5432/home
      - NODE_ENV=local
      - PORT=3000
      - JWT_SECRET=test
    env_file:
      - .env.example
    build:
      context: ./packages/home-apis
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    ports:
      - 3818:3000

volumes:
  postgres_db: #