version: "3"
services:
  postgres-db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES=home,auth
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - postgres_db:/data/postgres
    ports:
      - 5433:5432
  gateway-service:
    image: gateway-service
    container_name: gateway-service
    environment:
      - PORT=3000
      - SECRET_KEY=test
    depends_on:
      - auth-service
      - home-apis
    build:
      context: ./packages/gateway-service
      dockerfile: Dockerfile
    ports:
      - 3816:3000
  auth-service:
    image: auth-service
    container_name: auth-service
    environment:
      - DATABASE_URL=postgres://api:development_pass@postgres-db:5432/auth
      - PORT=3000
      - JWT_SECRET=test
      - NODE_ENV=local
    depends_on:
      - postgres-db
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    ports:
      - 3817:3000
  home-apis:
    image: home-apis
    container_name: home-apis
    environment:
      - DATABASE_URL=postgres://api:development_pass@postgres-db:5432/home
      - NODE_ENV=local
      - PORT=3000
      - JWT_SECRET=test
    depends_on:
      - postgres-db
    build:
      context: ./packages/home-apis
      dockerfile: Dockerfile
    ports:
      - 3818:3000
volumes:
  postgres_db:
    driver: local